//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ritual.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientIssuesFeedback
    {
        public ClientIssuesFeedback()
        {
            this.RitualLookupsComplaint = new HashSet<RitualLookup>();
            this.RitualLookupsCompliments = new HashSet<RitualLookup>();
            this.RitualLookupsIssueExercise = new HashSet<RitualLookup>();
            this.RitualLookupsIssueInjury = new HashSet<RitualLookup>();
            this.RitualLookupsIssueMobility = new HashSet<RitualLookup>();
            this.RitualLookupsIssueMovementPattern = new HashSet<RitualLookup>();
            this.RitualLookupsIssuePosture = new HashSet<RitualLookup>();
        }
    
        public int Id { get; set; }
        public int MemberId { get; set; }
        public int EmployeeId { get; set; }
        public string Type { get; set; }
        public System.DateTime DateRaised { get; set; }
        public string Status { get; set; }
        public string Details { get; set; }
        public string RecommendationAction { get; set; }
        public string ComplaintOther { get; set; }
        public string ComplimentOther { get; set; }
        public string IssueExerciseOther { get; set; }
        public string IssueInjuryOther { get; set; }
        public string IssueMobilityOther { get; set; }
        public string IssueMovementPatternOther { get; set; }
        public string IssuePostureOther { get; set; }
        public bool IssueInjuryRelevantToExercise { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Member Member { get; set; }
        public virtual ICollection<RitualLookup> RitualLookupsComplaint { get; set; }
        public virtual ICollection<RitualLookup> RitualLookupsCompliments { get; set; }
        public virtual ICollection<RitualLookup> RitualLookupsIssueExercise { get; set; }
        public virtual ICollection<RitualLookup> RitualLookupsIssueInjury { get; set; }
        public virtual ICollection<RitualLookup> RitualLookupsIssueMobility { get; set; }
        public virtual ICollection<RitualLookup> RitualLookupsIssueMovementPattern { get; set; }
        public virtual ICollection<RitualLookup> RitualLookupsIssuePosture { get; set; }
    }
}
