//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ritual.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InitialAssessment
    {
        public int Id { get; set; }
        public System.DateTime AssessmentDateTime { get; set; }
        public int MemberId { get; set; }
        public int EmployeeId { get; set; }
        public string ClientCheckDetails { get; set; }
        public string ClientHearAboutRitual { get; set; }
        public string ClientTrainingHistory { get; set; }
        public string ClientInjuriesMedicalIssues { get; set; }
        public string ClientPosturalArea { get; set; }
        public string ClientPosturalAreaDetails { get; set; }
        public string MovementAnteriorTrunk { get; set; }
        public string MovementPosteriorTrunk { get; set; }
        public string MovementHorizontalPush { get; set; }
        public string MovementVerticalPush { get; set; }
        public string MovementHorizontalPull { get; set; }
        public string MovementVerticalPull { get; set; }
        public string MovementHipPush { get; set; }
        public string MovementHipPull { get; set; }
        public string MovementSingleLeg { get; set; }
        public string MovementLocomotion1 { get; set; }
        public string MovementLocamotion2 { get; set; }
        public string MovementDetails { get; set; }
        public string Recommendation { get; set; }
        public bool WorkoutExplained { get; set; }
        public bool WarmupExplained { get; set; }
        public bool ClientEmployeeReminder { get; set; }
        public string AdditionalClientProgress { get; set; }
        public string AdditionalClientTips { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Member Member { get; set; }
    }
}
