//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ritual.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageLocationPrice
    {
        public int Id { get; set; }
        public int LocationId { get; set; }
        public int PackageId { get; set; }
        public decimal MonthlyPrice { get; set; }
        public decimal TotalPrice { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Package Package { get; set; }
    }
}
