//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ritual.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        public Package()
        {
            this.Memberships = new HashSet<Membership>();
            this.PackageLocationPrices = new HashSet<PackageLocationPrice>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int PackageTypeId { get; set; }
        public Nullable<int> PackagePeriodMonths { get; set; }
        public Nullable<int> PackageSuspensionLimit { get; set; }
        public Nullable<int> PackageVisitLimit { get; set; }
        public bool PackageIsActive { get; set; }
        public bool PackageIsReoccuring { get; set; }
        public bool PackagePayInFull { get; set; }
    
        public virtual ICollection<Membership> Memberships { get; set; }
        public virtual PackageType PackageType { get; set; }
        public virtual ICollection<PackageLocationPrice> PackageLocationPrices { get; set; }
    }
}
