//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ritual.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentSchedule
    {
        public int Id { get; set; }
        public int MemberId { get; set; }
        public int MembershipId { get; set; }
        public decimal Payment { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public byte Paid { get; set; }
        public string TransactionId { get; set; }
        public string Currency { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Membership Membership { get; set; }
    }
}
