//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ritual.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentHoliday
    {
        public int Id { get; set; }
        public int MembershipId { get; set; }
        public System.DateTime PaymentHolidayStartDate { get; set; }
        public System.DateTime PaymentHolidayEndDate { get; set; }
        public string PaymentHolidayReason { get; set; }
    
        public virtual Membership Membership { get; set; }
    }
}
