//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ritual.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RitualLookup
    {
        public RitualLookup()
        {
            this.ClientIssuesFeedbacks = new HashSet<ClientIssuesFeedback>();
            this.ClientIssuesFeedbacks1 = new HashSet<ClientIssuesFeedback>();
            this.ClientIssuesFeedbacks2 = new HashSet<ClientIssuesFeedback>();
            this.ClientIssuesFeedbacks3 = new HashSet<ClientIssuesFeedback>();
            this.ClientIssuesFeedbacks4 = new HashSet<ClientIssuesFeedback>();
            this.ClientIssuesFeedbacks5 = new HashSet<ClientIssuesFeedback>();
            this.ClientIssuesFeedbacks6 = new HashSet<ClientIssuesFeedback>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Category { get; set; }
    
        public virtual ICollection<ClientIssuesFeedback> ClientIssuesFeedbacks { get; set; }
        public virtual ICollection<ClientIssuesFeedback> ClientIssuesFeedbacks1 { get; set; }
        public virtual ICollection<ClientIssuesFeedback> ClientIssuesFeedbacks2 { get; set; }
        public virtual ICollection<ClientIssuesFeedback> ClientIssuesFeedbacks3 { get; set; }
        public virtual ICollection<ClientIssuesFeedback> ClientIssuesFeedbacks4 { get; set; }
        public virtual ICollection<ClientIssuesFeedback> ClientIssuesFeedbacks5 { get; set; }
        public virtual ICollection<ClientIssuesFeedback> ClientIssuesFeedbacks6 { get; set; }
    }
}
