//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ritual.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RitualLookup
    {
        public RitualLookup()
        {
            this.ClientIssuesFeedbacksComplaint = new HashSet<ClientIssuesFeedback>();
            this.ClientIssuesFeedbacksCompliments = new HashSet<ClientIssuesFeedback>();
            this.ClientIssuesFeedbackIssueExercise = new HashSet<ClientIssuesFeedback>();
            this.ClientIssuesFeedbackIssueInjury = new HashSet<ClientIssuesFeedback>();
            this.ClientIssuesFeedbackIssueMobility = new HashSet<ClientIssuesFeedback>();
            this.ClientIssuesFeedbackIssueMovementPattern = new HashSet<ClientIssuesFeedback>();
            this.ClientIssuesFeedbackIssuePosture = new HashSet<ClientIssuesFeedback>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Category { get; set; }
    
        public virtual ICollection<ClientIssuesFeedback> ClientIssuesFeedbacksComplaint { get; set; }
        public virtual ICollection<ClientIssuesFeedback> ClientIssuesFeedbacksCompliments { get; set; }
        public virtual ICollection<ClientIssuesFeedback> ClientIssuesFeedbackIssueExercise { get; set; }
        public virtual ICollection<ClientIssuesFeedback> ClientIssuesFeedbackIssueInjury { get; set; }
        public virtual ICollection<ClientIssuesFeedback> ClientIssuesFeedbackIssueMobility { get; set; }
        public virtual ICollection<ClientIssuesFeedback> ClientIssuesFeedbackIssueMovementPattern { get; set; }
        public virtual ICollection<ClientIssuesFeedback> ClientIssuesFeedbackIssuePosture { get; set; }
    }
}
