
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Ritual.Booking.Data
{

using System;
    using System.Collections.Generic;
    
public partial class AspNetUser
{

    public AspNetUser()
    {

        this.Employees = new HashSet<Employee>();

        this.Members = new HashSet<Member>();

        this.News = new HashSet<News>();

        this.News1 = new HashSet<News>();

    }


    public string Id { get; set; }

    public string Email { get; set; }

    public bool EmailConfirmed { get; set; }

    public string PasswordHash { get; set; }

    public string SecurityStamp { get; set; }

    public string PhoneNumber { get; set; }

    public bool PhoneNumberConfirmed { get; set; }

    public bool TwoFactorEnabled { get; set; }

    public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }

    public bool LockoutEnabled { get; set; }

    public int AccessFailedCount { get; set; }

    public string UserName { get; set; }

    public string Salutation { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public int Pin { get; set; }

    public string HomePhone { get; set; }

    public string MobilePhone { get; set; }



    public virtual ICollection<Employee> Employees { get; set; }

    public virtual ICollection<Member> Members { get; set; }

    public virtual ICollection<News> News { get; set; }

    public virtual ICollection<News> News1 { get; set; }

}

}
