

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Ritual.Booking.Data
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class RitualDBEntities : DbContext
{
    public RitualDBEntities()
        : base("name=RitualDBEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Location> Locations { get; set; }

    public virtual DbSet<Member> Members { get; set; }

    public virtual DbSet<Membership> Memberships { get; set; }

    public virtual DbSet<MembershipState> MembershipStates { get; set; }

    public virtual DbSet<MembershipSuspension> MembershipSuspensions { get; set; }

    public virtual DbSet<OpeningHour> OpeningHours { get; set; }

    public virtual DbSet<OpeningHourOverride> OpeningHourOverrides { get; set; }

    public virtual DbSet<Package> Packages { get; set; }

    public virtual DbSet<QuarterlyAssessment> QuarterlyAssessments { get; set; }

    public virtual DbSet<SessionBooking> SessionBookings { get; set; }

    public virtual DbSet<SessionBookingState> SessionBookingStates { get; set; }

    public virtual DbSet<TimeSlot> TimeSlots { get; set; }

    public virtual DbSet<Trainer> Trainers { get; set; }

    public virtual DbSet<AspNetUser> AspNetUsers { get; set; }

}

}

