//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ritual.Booking.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.Bookings = new HashSet<Booking>();
            this.Trainers = new HashSet<Trainer>();
            this.Trainers1 = new HashSet<Trainer>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public string PostCode { get; set; }
        public string Country { get; set; }
        public short TimeZoneOffset { get; set; }
        public System.Data.Entity.Spatial.DbGeography Coordinates { get; set; }
    
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual ICollection<Trainer> Trainers { get; set; }
        public virtual ICollection<Trainer> Trainers1 { get; set; }
    }
}
