//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ritual.Booking.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Membership
    {
        public int Id { get; set; }
        public int MemberId { get; set; }
        public int PackageId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public bool Trial { get; set; }
        public int MembershipStateId { get; set; }
        public Nullable<System.DateTime> CancellationDate { get; set; }
        public bool Paid { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual MembershipState MembershipState { get; set; }
    }
}
