
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Ritual.Booking.Data
{

using System;
    using System.Collections.Generic;
    
public partial class News
{

    public int Id { get; set; }

    public int LocationId { get; set; }

    public string Title { get; set; }

    public string Body { get; set; }

    public int NewsCategoryId { get; set; }

    public System.DateTime CreatedDate { get; set; }

    public System.DateTime ModifiedDate { get; set; }

    public string CreatedBy { get; set; }

    public string ModifiedBy { get; set; }



    public virtual AspNetUser AspNetUserCreatedBy { get; set; }

    public virtual AspNetUser AspNetUserModifiedBy { get; set; }

    public virtual Location Location { get; set; }

    public virtual NewsCategory NewsCategory { get; set; }

}

}
