
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Ritual.Booking.Data
{

using System;
    using System.Collections.Generic;
    
public partial class OpeningHourOverride
{

    public int Id { get; set; }

    public System.DateTime OverrideStartDate { get; set; }

    public System.DateTime OverrideEndDate { get; set; }

    public Nullable<byte> DayOfWeek { get; set; }

    public Nullable<System.TimeSpan> AltOpenTime { get; set; }

    public Nullable<System.TimeSpan> AltCloseTme { get; set; }

    public Nullable<bool> Closed { get; set; }

    public string OverrideReason { get; set; }

    public Nullable<int> LocationId { get; set; }



    public virtual Location Location { get; set; }

}

}
