
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Ritual.Booking.Data
{

using System;
    using System.Collections.Generic;
    
public partial class Package
{

    public Package()
    {

        this.Memberships = new HashSet<Membership>();

    }


    public int Id { get; set; }

    public string Name { get; set; }

    public string PackageType { get; set; }

    public Nullable<int> PackagePeriodMonths { get; set; }

    public Nullable<decimal> PackagePricePerMonth { get; set; }

    public Nullable<decimal> PackageDiscountPercentage { get; set; }

    public Nullable<decimal> PackageDiscountAmmount { get; set; }

    public Nullable<decimal> PackagePriceAfterDiscount { get; set; }

    public Nullable<decimal> PackageTotalPrice { get; set; }

    public Nullable<int> PackageSuspensionLimit { get; set; }

    public Nullable<int> PackageVisitLimit { get; set; }

    public Nullable<bool> PackageIsActive { get; set; }



    public virtual ICollection<Membership> Memberships { get; set; }

}

}
