
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Ritual.Booking.Data
{

using System;
    using System.Collections.Generic;
    
public partial class QuarterlyAssessment
{

    public int Id { get; set; }

    public string MemberId { get; set; }

    public int TrainerId { get; set; }

    public int QAQuarter { get; set; }

    public Nullable<int> QAYear { get; set; }

    public Nullable<System.DateTime> QADateTime { get; set; }

    public Nullable<int> QAClientRPE { get; set; }

    public string QATestOneTitle { get; set; }

    public string QATestOneType { get; set; }

    public string QATestOneTimeReps { get; set; }

    public string QATestOneNotes { get; set; }

    public string QATestTwoTitle { get; set; }

    public string QATestTwoType { get; set; }

    public string QATestTwoTimeReps { get; set; }

    public string QATestTwoNotes { get; set; }

    public string QATestThreeTitle { get; set; }

    public string QATestThreeType { get; set; }

    public string QATestThreeTimeReps { get; set; }

    public string QATestThreeNotes { get; set; }

    public string QATestFourTitle { get; set; }

    public string QATestFourType { get; set; }

    public string QATestFourTimeReps { get; set; }

    public string QATestFourNotes { get; set; }

    public string QATestFiveTitle { get; set; }

    public string QATestFiveType { get; set; }

    public string QATestFiveTimeReps { get; set; }

    public string QATestFiveNotes { get; set; }

    public Nullable<int> QATestFiveRoundOneReps { get; set; }

    public Nullable<int> QATestFiveRoundTwoReps { get; set; }

    public Nullable<int> QATestFiveRoundThreeReps { get; set; }

    public Nullable<int> QATestFiveRoundFourReps { get; set; }

    public Nullable<int> QATestFiveRoundFiveReps { get; set; }

    public Nullable<int> QATestFiveRoundSixReps { get; set; }

    public Nullable<int> QATestFiveRoundSevenReps { get; set; }

    public Nullable<int> QATestFiveRoundEightReps { get; set; }

    public Nullable<int> QATestFiveTotalReps { get; set; }



    public virtual Member Member { get; set; }

    public virtual Trainer Trainer { get; set; }

}

}
