
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Ritual.Booking.Data
{

using System;
    using System.Collections.Generic;
    
public partial class TimeSlot
{

    public TimeSlot()
    {

        this.SessionBookings = new HashSet<SessionBooking>();

    }


    public int Id { get; set; }

    public System.TimeSpan StartTime { get; set; }

    public System.TimeSpan EndTime { get; set; }



    public virtual ICollection<SessionBooking> SessionBookings { get; set; }

}

}
